import { useState } from 'react';
import { useClinic } from './ClinicContext';
import { doctors, slots, currency } from './clinic';
import { todayInColombo } from './appointment';
function Intro({ title, children }) { return <section className="page-intro"><span className="section-kicker">MEDSYNC · DEMO WORKSPACE</span><h1>{title}</h1><p>{children}</p></section>; }
export function DoctorsPage() {
  const [query, setQuery] = useState('');
  const [branch, setBranch] = useState('');
  const clinic = useClinic();
  const matches = doctors.filter(d => (!branch || d.branch === branch) && `${d.name} ${d.specialty}`.toLowerCase().includes(query.toLowerCase()));
  return <><Intro title="Find a doctor">Explore fictional doctors and consultation fees, then plan a demo visit.</Intro><section className="content-section"><div className="clinic-filters"><label className="clinic-field">Search doctors or specialties<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Name or specialty" /></label><label className="clinic-field">Branch<select value={branch} onChange={e => setBranch(e.target.value)}><option value="">All branches</option>{['Colombo', 'Kandy', 'Galle'].map(b => <option key={b}>{b}</option>)}</select></label></div><div className="doctor-grid">{matches.map(d => <article className="clinic-panel" key={d.id}><span className="doctor-avatar" aria-hidden="true">{d.name.split(' ').at(-1).slice(0, 1)}</span><h2>{d.name}</h2><p>{d.specialty}</p><p>{d.branch} branch</p><strong>{currency(d.fee)}</strong><p className="demo-note">Example profile · availability is simulated</p><a className="button button-blue" href="#/appointments" onClick={() => clinic?.setDraft({ branch: d.branch, doctor: d.id })}>Book with this doctor →</a></article>)}</div>{!matches.length && <p role="status">No matching doctors. Try another name or branch.</p>}</section></>;
}
function AppointmentItem({ booking: b }) {
  const { act } = useClinic();
  const [editing, setEditing] = useState(false);
  const [cancel, setCancel] = useState(false);
  const [date, setDate] = useState(b.date);
  const [time, setTime] = useState(b.time);
  const [message, setMessage] = useState('');
  function perform(action) { try { act(action); setEditing(false); setCancel(false); setMessage('Appointment updated.'); } catch (error) { setMessage(error.message); } }
  return <article className="clinic-panel"><div className="clinic-row"><h2>{doctors.find(d => d.id === b.doctor)?.name}</h2><span className={`status-pill ${b.status === 'Cancelled' ? 'muted' : ''}`}>{b.status}</span></div><p><strong>{b.id}</strong> · {b.name}</p><p>{b.branch} · {b.date} · {b.time} (Sri Lanka)</p><div className="clinic-actions"><a className="text-link" href={`#/billing/${b.id}`}>View invoice →</a>{b.status === 'Scheduled' && <><button className="button button-outline" onClick={() => { setEditing(!editing); setCancel(false); }}>Reschedule</button><button className="button button-outline" onClick={() => { setCancel(true); setEditing(false); }}>Cancel appointment</button></>}</div>
    {editing && <form className="inline-editor" onSubmit={e => { e.preventDefault(); perform({ type: 'reschedule', id: b.id, date, time }); }}><label className="clinic-field">New date<input type="date" min={todayInColombo()} required value={date} onChange={e => setDate(e.target.value)} /></label><label className="clinic-field">New time<select value={time} onChange={e => setTime(e.target.value)}>{slots.map(s => <option key={s}>{s}</option>)}</select></label><button className="button button-blue">Save change</button></form>}
    {cancel && <div className="inline-editor"><p>Cancel {b.id}? An unpaid demo invoice will be voided. Paid demo bookings cannot be cancelled because refunds are not implemented.</p><div className="clinic-actions"><button className="button button-blue" onClick={() => perform({ type: 'cancel', id: b.id })}>Confirm cancellation</button><button className="button button-outline" onClick={() => setCancel(false)}>Keep appointment</button></div></div>}
    {message && <p role="status">{message}</p>}
  </article>;
}
export function MyAppointmentsPage() {
  const { bookings = [] } = useClinic() || {};
  const [status, setStatus] = useState('All');
  return <><Intro title="My appointments">Review, reschedule or cancel the demo appointments created during this session.</Intro><section className="content-section"><div className="clinic-row"><label className="clinic-field">Status<select value={status} onChange={e => setStatus(e.target.value)}>{['All', 'Scheduled', 'Cancelled'].map(s => <option key={s}>{s}</option>)}</select></label><a className="button button-blue" href="#/appointments">+ New appointment</a></div><div className="clinic-stack">{bookings.filter(b => status === 'All' || b.status === status).map(b => <AppointmentItem key={b.id} booking={b} />)}</div>{!bookings.some(b => status === 'All' || b.status === status) && <div className="clinic-empty"><h2>No appointments here yet</h2><p>Create a demo booking to see it here. Reloading clears session data.</p><a href="#/doctors" className="text-link">Find a doctor →</a></div>}</section></>;
}
export function BillingPage({ itemId }) {
  const { bookings = [], act } = useClinic() || {};
  const [amount, setAmount] = useState('');
  const [message, setMessage] = useState('');
  const selected = bookings.find(b => b.id === itemId);
  const active = bookings.filter(b => b.status !== 'Cancelled');
  const totals = active.reduce((sum, b) => ({ billed: sum.billed + b.fee, paid: sum.paid + b.paid }), { billed: 0, paid: 0 });
  if (itemId) return <><Intro title="Invoice details">Demo invoice · no real payment will be collected.</Intro><section className="content-section"><a className="text-link" href="#/billing">← All invoices</a>{!selected ? <div className="clinic-empty"><h2>Invoice not found</h2><p>Demo invoices clear on reload. Create a new booking to continue.</p></div> : <article className="clinic-panel invoice"><div className="clinic-row"><h2>INV-{selected.id}</h2><span className="status-pill">{selected.status === 'Cancelled' ? 'Void' : selected.paid === selected.fee ? 'Paid (demo)' : 'Outstanding'}</span></div><p>{selected.name} · {selected.branch}<br />Consultation with {doctors.find(d => d.id === selected.doctor)?.name}<br />{selected.date} · {selected.time}</p><dl><dt>Consultation fee</dt><dd>{currency(selected.fee)}</dd><dt>Demo payments</dt><dd>{currency(selected.paid)}</dd><dt>Amount due</dt><dd>{currency(selected.status === 'Cancelled' ? 0 : selected.fee - selected.paid)}</dd></dl>{selected.status !== 'Cancelled' && selected.paid < selected.fee && <form className="inline-editor" onSubmit={e => { e.preventDefault(); try { act({ type: 'pay', id: selected.id, amount }); setAmount(''); setMessage('Simulated payment recorded. No money was charged.'); } catch (error) { setMessage(error.message); } }}><h3>Simulate a payment</h3><p>Testing only. Do not enter card or bank details.</p><label className="clinic-field">Amount (LKR)<input type="number" min="0.01" step="0.01" max={(selected.fee - selected.paid).toFixed(2)} value={amount} onChange={e => setAmount(e.target.value)} required /></label><button className="button button-blue">Record demo payment</button></form>}{message && <p role="status">{message}</p>}<h3>Payment history</h3>{selected.payments.length ? selected.payments.map(p => <p key={p.number}>Demo receipt {selected.id}-{p.number} · {currency(p.amount)}</p>) : <p>No payments recorded.</p>}<button className="button button-outline" onClick={() => window.print()}>Print demo invoice</button></article>}</section></>;
  return <><Intro title="Billing & invoices">Bookings automatically create demo invoices. Payments here are simulations.</Intro><section className="content-section"><div className="clinic-metrics"><article><span>Total billed</span><strong>{currency(totals.billed)}</strong></article><article><span>Demo payments</span><strong>{currency(totals.paid)}</strong></article><article><span>Outstanding</span><strong>{currency(totals.billed - totals.paid)}</strong></article></div><div className="clinic-stack">{bookings.map(b => <article className="clinic-panel clinic-row" key={b.id}><div><h2>INV-{b.id}</h2><p>{b.name} · {b.status === 'Cancelled' ? 'Void' : `${currency(b.fee - b.paid)} outstanding`}</p></div><a className="button button-outline" href={`#/billing/${b.id}`}>Open invoice →</a></article>)}</div>{!bookings.length && <div className="clinic-empty"><h2>No invoices yet</h2><p>An invoice appears after you confirm a demo booking.</p><a className="button button-blue" href="#/appointments">Book an appointment</a></div>}</section></>;
}
